// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MassoudBooksSr.proto

#ifndef PROTOBUF_INCLUDED_MassoudBooksSr_2eproto
#define PROTOBUF_INCLUDED_MassoudBooksSr_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_MassoudBooksSr_2eproto 

namespace protobuf_MassoudBooksSr_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_MassoudBooksSr_2eproto
namespace MassoudBookSerialization {
class Book;
class BookDefaultTypeInternal;
extern BookDefaultTypeInternal _Book_default_instance_;
class ToSerialize;
class ToSerializeDefaultTypeInternal;
extern ToSerializeDefaultTypeInternal _ToSerialize_default_instance_;
}  // namespace MassoudBookSerialization
namespace google {
namespace protobuf {
template<> ::MassoudBookSerialization::Book* Arena::CreateMaybeMessage<::MassoudBookSerialization::Book>(Arena*);
template<> ::MassoudBookSerialization::ToSerialize* Arena::CreateMaybeMessage<::MassoudBookSerialization::ToSerialize>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace MassoudBookSerialization {

// ===================================================================

class Book : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MassoudBookSerialization.Book) */ {
 public:
  Book();
  virtual ~Book();

  Book(const Book& from);

  inline Book& operator=(const Book& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Book(Book&& from) noexcept
    : Book() {
    *this = ::std::move(from);
  }

  inline Book& operator=(Book&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Book& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Book* internal_default_instance() {
    return reinterpret_cast<const Book*>(
               &_Book_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Book* other);
  friend void swap(Book& a, Book& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Book* New() const final {
    return CreateMaybeMessage<Book>(NULL);
  }

  Book* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Book>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Book& from);
  void MergeFrom(const Book& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Book* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string tag = 4;
  int tag_size() const;
  void clear_tag();
  static const int kTagFieldNumber = 4;
  const ::std::string& tag(int index) const;
  ::std::string* mutable_tag(int index);
  void set_tag(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_tag(int index, ::std::string&& value);
  #endif
  void set_tag(int index, const char* value);
  void set_tag(int index, const char* value, size_t size);
  ::std::string* add_tag();
  void add_tag(const ::std::string& value);
  #if LANG_CXX11
  void add_tag(::std::string&& value);
  #endif
  void add_tag(const char* value);
  void add_tag(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& tag() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_tag();

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string catagory = 2;
  void clear_catagory();
  static const int kCatagoryFieldNumber = 2;
  const ::std::string& catagory() const;
  void set_catagory(const ::std::string& value);
  #if LANG_CXX11
  void set_catagory(::std::string&& value);
  #endif
  void set_catagory(const char* value);
  void set_catagory(const char* value, size_t size);
  ::std::string* mutable_catagory();
  ::std::string* release_catagory();
  void set_allocated_catagory(::std::string* catagory);

  // string readingStatus = 3;
  void clear_readingstatus();
  static const int kReadingStatusFieldNumber = 3;
  const ::std::string& readingstatus() const;
  void set_readingstatus(const ::std::string& value);
  #if LANG_CXX11
  void set_readingstatus(::std::string&& value);
  #endif
  void set_readingstatus(const char* value);
  void set_readingstatus(const char* value, size_t size);
  ::std::string* mutable_readingstatus();
  ::std::string* release_readingstatus();
  void set_allocated_readingstatus(::std::string* readingstatus);

  // int32 pages = 5;
  void clear_pages();
  static const int kPagesFieldNumber = 5;
  ::google::protobuf::int32 pages() const;
  void set_pages(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MassoudBookSerialization.Book)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> tag_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr catagory_;
  ::google::protobuf::internal::ArenaStringPtr readingstatus_;
  ::google::protobuf::int32 pages_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_MassoudBooksSr_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ToSerialize : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MassoudBookSerialization.ToSerialize) */ {
 public:
  ToSerialize();
  virtual ~ToSerialize();

  ToSerialize(const ToSerialize& from);

  inline ToSerialize& operator=(const ToSerialize& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ToSerialize(ToSerialize&& from) noexcept
    : ToSerialize() {
    *this = ::std::move(from);
  }

  inline ToSerialize& operator=(ToSerialize&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ToSerialize& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ToSerialize* internal_default_instance() {
    return reinterpret_cast<const ToSerialize*>(
               &_ToSerialize_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ToSerialize* other);
  friend void swap(ToSerialize& a, ToSerialize& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ToSerialize* New() const final {
    return CreateMaybeMessage<ToSerialize>(NULL);
  }

  ToSerialize* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ToSerialize>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ToSerialize& from);
  void MergeFrom(const ToSerialize& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ToSerialize* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .MassoudBookSerialization.Book AllBooks = 1;
  int allbooks_size() const;
  void clear_allbooks();
  static const int kAllBooksFieldNumber = 1;
  ::MassoudBookSerialization::Book* mutable_allbooks(int index);
  ::google::protobuf::RepeatedPtrField< ::MassoudBookSerialization::Book >*
      mutable_allbooks();
  const ::MassoudBookSerialization::Book& allbooks(int index) const;
  ::MassoudBookSerialization::Book* add_allbooks();
  const ::google::protobuf::RepeatedPtrField< ::MassoudBookSerialization::Book >&
      allbooks() const;

  // repeated string Tags = 2;
  int tags_size() const;
  void clear_tags();
  static const int kTagsFieldNumber = 2;
  const ::std::string& tags(int index) const;
  ::std::string* mutable_tags(int index);
  void set_tags(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_tags(int index, ::std::string&& value);
  #endif
  void set_tags(int index, const char* value);
  void set_tags(int index, const char* value, size_t size);
  ::std::string* add_tags();
  void add_tags(const ::std::string& value);
  #if LANG_CXX11
  void add_tags(::std::string&& value);
  #endif
  void add_tags(const char* value);
  void add_tags(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& tags() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_tags();

  // @@protoc_insertion_point(class_scope:MassoudBookSerialization.ToSerialize)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::MassoudBookSerialization::Book > allbooks_;
  ::google::protobuf::RepeatedPtrField< ::std::string> tags_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_MassoudBooksSr_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Book

// string name = 1;
inline void Book::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Book::name() const {
  // @@protoc_insertion_point(field_get:MassoudBookSerialization.Book.name)
  return name_.GetNoArena();
}
inline void Book::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MassoudBookSerialization.Book.name)
}
#if LANG_CXX11
inline void Book::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MassoudBookSerialization.Book.name)
}
#endif
inline void Book::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MassoudBookSerialization.Book.name)
}
inline void Book::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MassoudBookSerialization.Book.name)
}
inline ::std::string* Book::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:MassoudBookSerialization.Book.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Book::release_name() {
  // @@protoc_insertion_point(field_release:MassoudBookSerialization.Book.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Book::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:MassoudBookSerialization.Book.name)
}

// string catagory = 2;
inline void Book::clear_catagory() {
  catagory_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Book::catagory() const {
  // @@protoc_insertion_point(field_get:MassoudBookSerialization.Book.catagory)
  return catagory_.GetNoArena();
}
inline void Book::set_catagory(const ::std::string& value) {
  
  catagory_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MassoudBookSerialization.Book.catagory)
}
#if LANG_CXX11
inline void Book::set_catagory(::std::string&& value) {
  
  catagory_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MassoudBookSerialization.Book.catagory)
}
#endif
inline void Book::set_catagory(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  catagory_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MassoudBookSerialization.Book.catagory)
}
inline void Book::set_catagory(const char* value, size_t size) {
  
  catagory_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MassoudBookSerialization.Book.catagory)
}
inline ::std::string* Book::mutable_catagory() {
  
  // @@protoc_insertion_point(field_mutable:MassoudBookSerialization.Book.catagory)
  return catagory_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Book::release_catagory() {
  // @@protoc_insertion_point(field_release:MassoudBookSerialization.Book.catagory)
  
  return catagory_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Book::set_allocated_catagory(::std::string* catagory) {
  if (catagory != NULL) {
    
  } else {
    
  }
  catagory_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), catagory);
  // @@protoc_insertion_point(field_set_allocated:MassoudBookSerialization.Book.catagory)
}

// string readingStatus = 3;
inline void Book::clear_readingstatus() {
  readingstatus_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Book::readingstatus() const {
  // @@protoc_insertion_point(field_get:MassoudBookSerialization.Book.readingStatus)
  return readingstatus_.GetNoArena();
}
inline void Book::set_readingstatus(const ::std::string& value) {
  
  readingstatus_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MassoudBookSerialization.Book.readingStatus)
}
#if LANG_CXX11
inline void Book::set_readingstatus(::std::string&& value) {
  
  readingstatus_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MassoudBookSerialization.Book.readingStatus)
}
#endif
inline void Book::set_readingstatus(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  readingstatus_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MassoudBookSerialization.Book.readingStatus)
}
inline void Book::set_readingstatus(const char* value, size_t size) {
  
  readingstatus_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MassoudBookSerialization.Book.readingStatus)
}
inline ::std::string* Book::mutable_readingstatus() {
  
  // @@protoc_insertion_point(field_mutable:MassoudBookSerialization.Book.readingStatus)
  return readingstatus_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Book::release_readingstatus() {
  // @@protoc_insertion_point(field_release:MassoudBookSerialization.Book.readingStatus)
  
  return readingstatus_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Book::set_allocated_readingstatus(::std::string* readingstatus) {
  if (readingstatus != NULL) {
    
  } else {
    
  }
  readingstatus_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), readingstatus);
  // @@protoc_insertion_point(field_set_allocated:MassoudBookSerialization.Book.readingStatus)
}

// repeated string tag = 4;
inline int Book::tag_size() const {
  return tag_.size();
}
inline void Book::clear_tag() {
  tag_.Clear();
}
inline const ::std::string& Book::tag(int index) const {
  // @@protoc_insertion_point(field_get:MassoudBookSerialization.Book.tag)
  return tag_.Get(index);
}
inline ::std::string* Book::mutable_tag(int index) {
  // @@protoc_insertion_point(field_mutable:MassoudBookSerialization.Book.tag)
  return tag_.Mutable(index);
}
inline void Book::set_tag(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:MassoudBookSerialization.Book.tag)
  tag_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void Book::set_tag(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:MassoudBookSerialization.Book.tag)
  tag_.Mutable(index)->assign(std::move(value));
}
#endif
inline void Book::set_tag(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  tag_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MassoudBookSerialization.Book.tag)
}
inline void Book::set_tag(int index, const char* value, size_t size) {
  tag_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MassoudBookSerialization.Book.tag)
}
inline ::std::string* Book::add_tag() {
  // @@protoc_insertion_point(field_add_mutable:MassoudBookSerialization.Book.tag)
  return tag_.Add();
}
inline void Book::add_tag(const ::std::string& value) {
  tag_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MassoudBookSerialization.Book.tag)
}
#if LANG_CXX11
inline void Book::add_tag(::std::string&& value) {
  tag_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:MassoudBookSerialization.Book.tag)
}
#endif
inline void Book::add_tag(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  tag_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MassoudBookSerialization.Book.tag)
}
inline void Book::add_tag(const char* value, size_t size) {
  tag_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MassoudBookSerialization.Book.tag)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Book::tag() const {
  // @@protoc_insertion_point(field_list:MassoudBookSerialization.Book.tag)
  return tag_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Book::mutable_tag() {
  // @@protoc_insertion_point(field_mutable_list:MassoudBookSerialization.Book.tag)
  return &tag_;
}

// int32 pages = 5;
inline void Book::clear_pages() {
  pages_ = 0;
}
inline ::google::protobuf::int32 Book::pages() const {
  // @@protoc_insertion_point(field_get:MassoudBookSerialization.Book.pages)
  return pages_;
}
inline void Book::set_pages(::google::protobuf::int32 value) {
  
  pages_ = value;
  // @@protoc_insertion_point(field_set:MassoudBookSerialization.Book.pages)
}

// -------------------------------------------------------------------

// ToSerialize

// repeated .MassoudBookSerialization.Book AllBooks = 1;
inline int ToSerialize::allbooks_size() const {
  return allbooks_.size();
}
inline void ToSerialize::clear_allbooks() {
  allbooks_.Clear();
}
inline ::MassoudBookSerialization::Book* ToSerialize::mutable_allbooks(int index) {
  // @@protoc_insertion_point(field_mutable:MassoudBookSerialization.ToSerialize.AllBooks)
  return allbooks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::MassoudBookSerialization::Book >*
ToSerialize::mutable_allbooks() {
  // @@protoc_insertion_point(field_mutable_list:MassoudBookSerialization.ToSerialize.AllBooks)
  return &allbooks_;
}
inline const ::MassoudBookSerialization::Book& ToSerialize::allbooks(int index) const {
  // @@protoc_insertion_point(field_get:MassoudBookSerialization.ToSerialize.AllBooks)
  return allbooks_.Get(index);
}
inline ::MassoudBookSerialization::Book* ToSerialize::add_allbooks() {
  // @@protoc_insertion_point(field_add:MassoudBookSerialization.ToSerialize.AllBooks)
  return allbooks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MassoudBookSerialization::Book >&
ToSerialize::allbooks() const {
  // @@protoc_insertion_point(field_list:MassoudBookSerialization.ToSerialize.AllBooks)
  return allbooks_;
}

// repeated string Tags = 2;
inline int ToSerialize::tags_size() const {
  return tags_.size();
}
inline void ToSerialize::clear_tags() {
  tags_.Clear();
}
inline const ::std::string& ToSerialize::tags(int index) const {
  // @@protoc_insertion_point(field_get:MassoudBookSerialization.ToSerialize.Tags)
  return tags_.Get(index);
}
inline ::std::string* ToSerialize::mutable_tags(int index) {
  // @@protoc_insertion_point(field_mutable:MassoudBookSerialization.ToSerialize.Tags)
  return tags_.Mutable(index);
}
inline void ToSerialize::set_tags(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:MassoudBookSerialization.ToSerialize.Tags)
  tags_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ToSerialize::set_tags(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:MassoudBookSerialization.ToSerialize.Tags)
  tags_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ToSerialize::set_tags(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  tags_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MassoudBookSerialization.ToSerialize.Tags)
}
inline void ToSerialize::set_tags(int index, const char* value, size_t size) {
  tags_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MassoudBookSerialization.ToSerialize.Tags)
}
inline ::std::string* ToSerialize::add_tags() {
  // @@protoc_insertion_point(field_add_mutable:MassoudBookSerialization.ToSerialize.Tags)
  return tags_.Add();
}
inline void ToSerialize::add_tags(const ::std::string& value) {
  tags_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MassoudBookSerialization.ToSerialize.Tags)
}
#if LANG_CXX11
inline void ToSerialize::add_tags(::std::string&& value) {
  tags_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:MassoudBookSerialization.ToSerialize.Tags)
}
#endif
inline void ToSerialize::add_tags(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  tags_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MassoudBookSerialization.ToSerialize.Tags)
}
inline void ToSerialize::add_tags(const char* value, size_t size) {
  tags_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MassoudBookSerialization.ToSerialize.Tags)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ToSerialize::tags() const {
  // @@protoc_insertion_point(field_list:MassoudBookSerialization.ToSerialize.Tags)
  return tags_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ToSerialize::mutable_tags() {
  // @@protoc_insertion_point(field_mutable_list:MassoudBookSerialization.ToSerialize.Tags)
  return &tags_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace MassoudBookSerialization

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_MassoudBooksSr_2eproto
