// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MassoudBooksSr.proto
#include "stdafx.h"
#include "MassoudBooksSr.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_MassoudBooksSr_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_MassoudBooksSr_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Book;
}  // namespace protobuf_MassoudBooksSr_2eproto
namespace MassoudBookSerialization {
class BookDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Book>
      _instance;
} _Book_default_instance_;
class ToSerializeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ToSerialize>
      _instance;
} _ToSerialize_default_instance_;
}  // namespace MassoudBookSerialization
namespace protobuf_MassoudBooksSr_2eproto {
static void InitDefaultsBook() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MassoudBookSerialization::_Book_default_instance_;
    new (ptr) ::MassoudBookSerialization::Book();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MassoudBookSerialization::Book::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Book =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBook}, {}};

static void InitDefaultsToSerialize() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MassoudBookSerialization::_ToSerialize_default_instance_;
    new (ptr) ::MassoudBookSerialization::ToSerialize();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MassoudBookSerialization::ToSerialize::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ToSerialize =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsToSerialize}, {
      &protobuf_MassoudBooksSr_2eproto::scc_info_Book.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Book.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ToSerialize.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MassoudBookSerialization::Book, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MassoudBookSerialization::Book, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MassoudBookSerialization::Book, catagory_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MassoudBookSerialization::Book, readingstatus_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MassoudBookSerialization::Book, tag_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MassoudBookSerialization::Book, pages_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MassoudBookSerialization::ToSerialize, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MassoudBookSerialization::ToSerialize, allbooks_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MassoudBookSerialization::ToSerialize, tags_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MassoudBookSerialization::Book)},
  { 10, -1, sizeof(::MassoudBookSerialization::ToSerialize)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::MassoudBookSerialization::_Book_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::MassoudBookSerialization::_ToSerialize_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "MassoudBooksSr.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024MassoudBooksSr.proto\022\030MassoudBookSeria"
      "lization\"Y\n\004Book\022\014\n\004name\030\001 \001(\t\022\020\n\010catago"
      "ry\030\002 \001(\t\022\025\n\rreadingStatus\030\003 \001(\t\022\013\n\003tag\030\004"
      " \003(\t\022\r\n\005pages\030\005 \001(\005\"M\n\013ToSerialize\0220\n\010Al"
      "lBooks\030\001 \003(\0132\036.MassoudBookSerialization."
      "Book\022\014\n\004Tags\030\002 \003(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 226);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MassoudBooksSr.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_MassoudBooksSr_2eproto
namespace MassoudBookSerialization {

// ===================================================================

void Book::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Book::kNameFieldNumber;
const int Book::kCatagoryFieldNumber;
const int Book::kReadingStatusFieldNumber;
const int Book::kTagFieldNumber;
const int Book::kPagesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Book::Book()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MassoudBooksSr_2eproto::scc_info_Book.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MassoudBookSerialization.Book)
}
Book::Book(const Book& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      tag_(from.tag_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  catagory_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.catagory().size() > 0) {
    catagory_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.catagory_);
  }
  readingstatus_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.readingstatus().size() > 0) {
    readingstatus_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.readingstatus_);
  }
  pages_ = from.pages_;
  // @@protoc_insertion_point(copy_constructor:MassoudBookSerialization.Book)
}

void Book::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  catagory_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  readingstatus_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pages_ = 0;
}

Book::~Book() {
  // @@protoc_insertion_point(destructor:MassoudBookSerialization.Book)
  SharedDtor();
}

void Book::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  catagory_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  readingstatus_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Book::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Book::descriptor() {
  ::protobuf_MassoudBooksSr_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MassoudBooksSr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Book& Book::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MassoudBooksSr_2eproto::scc_info_Book.base);
  return *internal_default_instance();
}


void Book::Clear() {
// @@protoc_insertion_point(message_clear_start:MassoudBookSerialization.Book)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tag_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  catagory_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  readingstatus_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pages_ = 0;
  _internal_metadata_.Clear();
}

bool Book::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MassoudBookSerialization.Book)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MassoudBookSerialization.Book.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string catagory = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_catagory()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->catagory().data(), static_cast<int>(this->catagory().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MassoudBookSerialization.Book.catagory"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string readingStatus = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_readingstatus()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->readingstatus().data(), static_cast<int>(this->readingstatus().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MassoudBookSerialization.Book.readingStatus"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string tag = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_tag()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->tag(this->tag_size() - 1).data(),
            static_cast<int>(this->tag(this->tag_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MassoudBookSerialization.Book.tag"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 pages = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pages_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MassoudBookSerialization.Book)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MassoudBookSerialization.Book)
  return false;
#undef DO_
}

void Book::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MassoudBookSerialization.Book)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.Book.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string catagory = 2;
  if (this->catagory().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->catagory().data(), static_cast<int>(this->catagory().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.Book.catagory");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->catagory(), output);
  }

  // string readingStatus = 3;
  if (this->readingstatus().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->readingstatus().data(), static_cast<int>(this->readingstatus().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.Book.readingStatus");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->readingstatus(), output);
  }

  // repeated string tag = 4;
  for (int i = 0, n = this->tag_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tag(i).data(), static_cast<int>(this->tag(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.Book.tag");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->tag(i), output);
  }

  // int32 pages = 5;
  if (this->pages() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->pages(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MassoudBookSerialization.Book)
}

::google::protobuf::uint8* Book::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MassoudBookSerialization.Book)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.Book.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string catagory = 2;
  if (this->catagory().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->catagory().data(), static_cast<int>(this->catagory().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.Book.catagory");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->catagory(), target);
  }

  // string readingStatus = 3;
  if (this->readingstatus().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->readingstatus().data(), static_cast<int>(this->readingstatus().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.Book.readingStatus");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->readingstatus(), target);
  }

  // repeated string tag = 4;
  for (int i = 0, n = this->tag_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tag(i).data(), static_cast<int>(this->tag(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.Book.tag");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->tag(i), target);
  }

  // int32 pages = 5;
  if (this->pages() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->pages(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MassoudBookSerialization.Book)
  return target;
}

size_t Book::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MassoudBookSerialization.Book)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string tag = 4;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->tag_size());
  for (int i = 0, n = this->tag_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->tag(i));
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string catagory = 2;
  if (this->catagory().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->catagory());
  }

  // string readingStatus = 3;
  if (this->readingstatus().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->readingstatus());
  }

  // int32 pages = 5;
  if (this->pages() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pages());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Book::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MassoudBookSerialization.Book)
  GOOGLE_DCHECK_NE(&from, this);
  const Book* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Book>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MassoudBookSerialization.Book)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MassoudBookSerialization.Book)
    MergeFrom(*source);
  }
}

void Book::MergeFrom(const Book& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MassoudBookSerialization.Book)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tag_.MergeFrom(from.tag_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.catagory().size() > 0) {

    catagory_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.catagory_);
  }
  if (from.readingstatus().size() > 0) {

    readingstatus_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.readingstatus_);
  }
  if (from.pages() != 0) {
    set_pages(from.pages());
  }
}

void Book::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MassoudBookSerialization.Book)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Book::CopyFrom(const Book& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MassoudBookSerialization.Book)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Book::IsInitialized() const {
  return true;
}

void Book::Swap(Book* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Book::InternalSwap(Book* other) {
  using std::swap;
  tag_.InternalSwap(CastToBase(&other->tag_));
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  catagory_.Swap(&other->catagory_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  readingstatus_.Swap(&other->readingstatus_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(pages_, other->pages_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Book::GetMetadata() const {
  protobuf_MassoudBooksSr_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MassoudBooksSr_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ToSerialize::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ToSerialize::kAllBooksFieldNumber;
const int ToSerialize::kTagsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ToSerialize::ToSerialize()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MassoudBooksSr_2eproto::scc_info_ToSerialize.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MassoudBookSerialization.ToSerialize)
}
ToSerialize::ToSerialize(const ToSerialize& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      allbooks_(from.allbooks_),
      tags_(from.tags_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:MassoudBookSerialization.ToSerialize)
}

void ToSerialize::SharedCtor() {
}

ToSerialize::~ToSerialize() {
  // @@protoc_insertion_point(destructor:MassoudBookSerialization.ToSerialize)
  SharedDtor();
}

void ToSerialize::SharedDtor() {
}

void ToSerialize::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ToSerialize::descriptor() {
  ::protobuf_MassoudBooksSr_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MassoudBooksSr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ToSerialize& ToSerialize::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MassoudBooksSr_2eproto::scc_info_ToSerialize.base);
  return *internal_default_instance();
}


void ToSerialize::Clear() {
// @@protoc_insertion_point(message_clear_start:MassoudBookSerialization.ToSerialize)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  allbooks_.Clear();
  tags_.Clear();
  _internal_metadata_.Clear();
}

bool ToSerialize::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MassoudBookSerialization.ToSerialize)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .MassoudBookSerialization.Book AllBooks = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_allbooks()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string Tags = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_tags()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->tags(this->tags_size() - 1).data(),
            static_cast<int>(this->tags(this->tags_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MassoudBookSerialization.ToSerialize.Tags"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MassoudBookSerialization.ToSerialize)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MassoudBookSerialization.ToSerialize)
  return false;
#undef DO_
}

void ToSerialize::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MassoudBookSerialization.ToSerialize)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .MassoudBookSerialization.Book AllBooks = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->allbooks_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->allbooks(static_cast<int>(i)),
      output);
  }

  // repeated string Tags = 2;
  for (int i = 0, n = this->tags_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tags(i).data(), static_cast<int>(this->tags(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.ToSerialize.Tags");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->tags(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MassoudBookSerialization.ToSerialize)
}

::google::protobuf::uint8* ToSerialize::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MassoudBookSerialization.ToSerialize)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .MassoudBookSerialization.Book AllBooks = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->allbooks_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->allbooks(static_cast<int>(i)), deterministic, target);
  }

  // repeated string Tags = 2;
  for (int i = 0, n = this->tags_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tags(i).data(), static_cast<int>(this->tags(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MassoudBookSerialization.ToSerialize.Tags");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->tags(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MassoudBookSerialization.ToSerialize)
  return target;
}

size_t ToSerialize::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MassoudBookSerialization.ToSerialize)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .MassoudBookSerialization.Book AllBooks = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->allbooks_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->allbooks(static_cast<int>(i)));
    }
  }

  // repeated string Tags = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->tags_size());
  for (int i = 0, n = this->tags_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->tags(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ToSerialize::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MassoudBookSerialization.ToSerialize)
  GOOGLE_DCHECK_NE(&from, this);
  const ToSerialize* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ToSerialize>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MassoudBookSerialization.ToSerialize)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MassoudBookSerialization.ToSerialize)
    MergeFrom(*source);
  }
}

void ToSerialize::MergeFrom(const ToSerialize& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MassoudBookSerialization.ToSerialize)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  allbooks_.MergeFrom(from.allbooks_);
  tags_.MergeFrom(from.tags_);
}

void ToSerialize::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MassoudBookSerialization.ToSerialize)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ToSerialize::CopyFrom(const ToSerialize& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MassoudBookSerialization.ToSerialize)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ToSerialize::IsInitialized() const {
  return true;
}

void ToSerialize::Swap(ToSerialize* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ToSerialize::InternalSwap(ToSerialize* other) {
  using std::swap;
  CastToBase(&allbooks_)->InternalSwap(CastToBase(&other->allbooks_));
  tags_.InternalSwap(CastToBase(&other->tags_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ToSerialize::GetMetadata() const {
  protobuf_MassoudBooksSr_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MassoudBooksSr_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace MassoudBookSerialization
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MassoudBookSerialization::Book* Arena::CreateMaybeMessage< ::MassoudBookSerialization::Book >(Arena* arena) {
  return Arena::CreateInternal< ::MassoudBookSerialization::Book >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MassoudBookSerialization::ToSerialize* Arena::CreateMaybeMessage< ::MassoudBookSerialization::ToSerialize >(Arena* arena) {
  return Arena::CreateInternal< ::MassoudBookSerialization::ToSerialize >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
